title: "Buttons"
description: |
  Buttons will be used on every page throughout our website to keep it clean and organized.

patterns:
  basic:
    title: "Basic"
    description: |
      This button will be used throughout the website.
    width: "12em"
    fields:
      - name: text
        type: string
        example: "Submit"
      - name: url
        type: url
        example: "#"

  submit:
    title: "Submit"
    description: This is only for my form, for the submit button
    width: 200
    fields:
      - name: text
        type: string
        example: "Contact"
      - name: url
        type: url
        example: "#"
