title: "Buttons"
description: |
Buttons will be used on every page throughout our website to keep it clean and organized.

patterns:
  basic:
    title: "Basic"
    description: |
    This button will be used throughout the website.
    width: "12em"
