title: "Cards"
description: |
  Cards can be used to display information in an organized way.

patterns:
  basic:
    title: "Basic"
    description: |
      A simple card that contains a title and description.
    fields:
      - name: image
        type: string
        example: "/images/placeholder.jpg"
      - name: title
        type: string
        example: "Example Title"
      - name: description
        type: string
        example: "Example Description"
