title: "Banner"
description: |
  "The banner will be used on a couple of the pages to invite the cat-loving reader."

patterns:
  buttons:
    title: "Banner"
    description: |
      This banner will be used throughout the website.
    fields:
      - name: text
        type: string
        example: "Heading"
      - name: sub-text
        type: string
        example: "Sub Heading"
